# Generated by Django 4.2 on 2024-02-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='emal_list',
            new_name='email_list',
        ),
    ]
