# Generated by Django 4.2 on 2024-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='percentage_changed',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
